#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),THREE=require('three');
const {PNG}=require('pngjs');
const J=new Map(),M=new Map(),T=new Map();
const BIOME_TINT={grass_block_top:[89,167,51],grass_block_side_overlay:[89,167,51],oak_leaves:[60,192,41],spruce_leaves:[42,75,50],birch_leaves:[108,169,72],jungle_leaves:[51,145,30],acacia_leaves:[74,145,49],dark_oak_leaves:[56,130,38],azalea_leaves:[82,145,65],mangrove_leaves:[68,161,62],cherry_leaves:[231,178,178]};
// MC 26.2 vanilla redstone wire colors (RedStoneWireBlock.lambda$static$0)
// power=0: dark red, power=15: bright red. Source: decompiled RedStoneWireBlock.class
// Formula: r = power*0.6 + (0.4 if power>0 else 0.3)
//          g = clamp(power*power*0.7 - 0.5, 0, 1)
//          b = clamp(power*power*0.6 - 0.7, 0, 1)
const REDSTONE_COLORS={0:[76,0,0],1:[112,0,0],2:[122,0,0],3:[133,0,0],4:[143,0,0],5:[153,0,0],6:[163,0,0],7:[173,0,0],8:[184,0,0],9:[194,0,0],10:[204,0,0],11:[214,0,0],12:[224,0,0],13:[235,7,0],14:[245,28,0],15:[255,51,0]};
const V={east:[[1,0,0],[1,0,1],[1,1,1],[1,1,0]],west:[[0,0,1],[0,0,0],[0,1,0],[0,1,1]],up:[[0,1,0],[1,1,0],[1,1,1],[0,1,1]],down:[[0,0,1],[1,0,1],[1,0,0],[0,0,0]],south:[[1,0,1],[0,0,1],[0,1,1],[1,1,1]],north:[[0,0,0],[1,0,0],[1,1,0],[0,1,0]]};
const FACE_NORMALS_BASE={east:[1,0,0],west:[-1,0,0],up:[0,1,0],down:[0,-1,0],south:[0,0,1],north:[0,0,-1]};
const UV=[[0,16],[16,16],[16,0],[0,0]];
function json(f){if(!J.has(f))J.set(f,JSON.parse(fs.readFileSync(f)));return J.get(f)}
function strip(s,k='block'){return String(s||'').replace(/^minecraft:/,'').replace(new RegExp(`^${k}/`),'')}
function model(assets,id,seen=new Set()){
 id=strip(id);if(M.has(id))return M.get(id);if(seen.has(id))throw Error(`model parent cycle: ${id}`);
 const f=path.join(assets,'models/block',id+'.json');if(!fs.existsSync(f))return null;const r=json(f),p=r.parent?model(assets,r.parent,new Set([...seen,id])):null;
 const tx={...(p?.textures||{}),...(r.textures||{})};const out={textures:tx,elements:r.elements??p?.elements??[]};M.set(id,out);return out;
}
function resolveTexture(m,v){const seen=new Set();if(v&&typeof v==='object')v=v.sprite;while(typeof v==='string'&&v.startsWith('#')&&!seen.has(v)){seen.add(v);v=m.textures[v.slice(1)];if(v&&typeof v==='object')v=v.sprite}return typeof v==='string'?strip(v):null}
function match(w,p){if(!w)return true;if(w.OR)return w.OR.some(x=>match(x,p));if(w.AND)return w.AND.every(x=>match(x,p));return Object.entries(w).every(([k,v])=>String(v).split('|').includes(String(p[k])))}
function one(v){return Array.isArray(v)?(v.length?[v[0]]:[]):v?[v]:[]}
function multipart(v){return one(v).map(a=>({...a,y:a.y?(360-a.y)%360:0}))}
function applications(assets,b){const f=path.join(assets,'blockstates',strip(b.id)+'.json');if(!fs.existsSync(f))return[];const s=json(f),out=[];
 if(s.variants){let fallback;for(const[k,v]of Object.entries(s.variants)){fallback??=v;const q=Object.fromEntries(k.split(',').filter(Boolean).map(x=>x.split('=')));if(Object.entries(q).every(([a,z])=>String(b.properties[a])===z)){out.push(...one(v));fallback=null;break}}if(!out.length&&fallback)out.push(...one(fallback))}
 for(const p of s.multipart||[])if(match(p.when,b.properties))out.push(...multipart(p.apply));return out}
function biomeTint(textureName,data){const color=BIOME_TINT[textureName];if(!color)return data;const out=Buffer.from(data);for(let i=0;i<out.length;i+=4){out[i]=Math.round(out[i]*color[0]/255);out[i+1]=Math.round(out[i+1]*color[1]/255);out[i+2]=Math.round(out[i+2]*color[2]/255)}return out}
function redstoneTint(power,data){const color=REDSTONE_COLORS[Math.min(15,Math.max(0,+power||0))];if(!color)return data;const out=Buffer.from(data);for(let i=0;i<out.length;i+=4){out[i]=Math.round(out[i]*color[0]/255);out[i+1]=Math.round(out[i+1]*color[1]/255);out[i+2]=Math.round(out[i+2]*color[2]/255)}return out}
function texture(assets,n,power=null){n=strip(n);const redstone=power!==null&&(n==='redstone'||n.startsWith('redstone_dust')),key=redstone?`${n}:power=${Math.min(15,Math.max(0,+power||0))}`:n;if(T.has(key))return T.get(key);const f=path.join(assets,'textures/block',n+'.png');if(!fs.existsSync(f))return null;const p=PNG.sync.read(fs.readFileSync(f));let data=biomeTint(n,p.data);if(redstone)data=redstoneTint(power,data);const o={width:p.width,height:Math.min(p.width,p.height),data};T.set(key,o);return o}
function entityTexture(assets,n){n=strip(n,'entity');const key=`entity:${n}`;if(T.has(key))return T.get(key);const f=path.join(assets,'textures/entity',n+'.png');if(!fs.existsSync(f))return null;const p=PNG.sync.read(fs.readFileSync(f)),o={width:p.width,height:p.height,data:p.data};T.set(key,o);return o}
function waterTint(tx){if(tx.water)return tx.water;const data=Buffer.from(tx.data);for(let i=0;i<data.length;i+=4){const light=data[i]/255;data[i]=Math.round(64*light);data[i+1]=Math.round(118*light);data[i+2]=Math.round(228*light)}return tx.water={width:tx.width,height:tx.height,data}}
function uvs(face){const u=face.uv||[0,0,16,16];let q=[[u[0],u[3]],[u[2],u[3]],[u[2],u[1]],[u[0],u[1]]];for(let i=0;i<(+face.rotation||0)/90;i++)q=[q[1],q[2],q[3],q[0]];return q}
function matrix(e,a){const m=new THREE.Matrix4();if(e.rotation){const o=new THREE.Vector3(...(e.rotation.origin||[8,8,8])).multiplyScalar(1/16),axis=new THREE.Vector3(e.rotation.axis==='x'?1:0,e.rotation.axis==='y'?1:0,e.rotation.axis==='z'?1:0);m.premultiply(new THREE.Matrix4().makeTranslation(...o.clone().multiplyScalar(-1))).premultiply(new THREE.Matrix4().makeRotationAxis(axis,THREE.MathUtils.degToRad(e.rotation.angle||0))).premultiply(new THREE.Matrix4().makeTranslation(...o))}
 const c=.5,r=new THREE.Matrix4().makeTranslation(-c,-c,-c);r.premultiply(new THREE.Matrix4().makeRotationY(THREE.MathUtils.degToRad(a.y||0))).premultiply(new THREE.Matrix4().makeRotationX(THREE.MathUtils.degToRad(a.x||0))).premultiply(new THREE.Matrix4().makeTranslation(c,c,c));return r.multiply(m)}
function faceNormal(d,mx=new THREE.Matrix4()){const rotation=new THREE.Matrix4().extractRotation(mx);return new THREE.Vector3(...FACE_NORMALS_BASE[d]).applyMatrix4(rotation).normalize().toArray()}
function addModel(scene,assets,b,a){const m=model(assets,a.model);if(!m)return 0;let n=0,redstone=strip(b.id)==='redstone_wire';for(const e of m.elements){const lo=e.from.map(x=>x/16),hi=e.to.map(x=>x/16),flat=Math.abs(hi[0]-lo[0])<1e-6||Math.abs(hi[1]-lo[1])<1e-6||Math.abs(hi[2]-lo[2])<1e-6,pad=flat?0.001:0,mx=matrix(e,a);for(const[d,f]of Object.entries(e.faces||{})){const tx=texture(assets,resolveTexture(m,f.texture),redstone?b.properties.power:null);if(!tx)continue;const vs=V[d].map(([x,y,z])=>new THREE.Vector3(x?hi[0]+(d==='east'?pad:-pad):lo[0]-(d==='west'?pad:0),y?hi[1]+(d==='up'?pad:-pad):lo[1]-(d==='down'?pad:0),z?hi[2]+(d==='south'?pad:-pad):lo[2]-(d==='north'?pad:0)).applyMatrix4(mx).add(new THREE.Vector3(b.x,b.y,b.z)));scene.push({vs,uv:uvs(f),tx,alpha:1,dir:d,normal:faceNormal(d,mx),depthBias:redstone?-.004:0});n++}}return n}
function addBox(scene,lo,hi,tx,mx=new THREE.Matrix4()){for(const[d,q]of Object.entries(V))scene.push({vs:q.map(([x,y,z])=>new THREE.Vector3(x?hi[0]:lo[0],y?hi[1]:lo[1],z?hi[2]:lo[2]).applyMatrix4(mx)),uv:UV,tx,alpha:1,dir:d,normal:faceNormal(d,mx)})}
function addEntityBlockModel(scene,assets,name,mx,scale=.75,y=.45,height=.45){const m=model(assets,name);if(!m)return 0;let n=0;for(const e of m.elements){const lo=e.from.map(x=>x/16),hi=e.to.map(x=>x/16),em=matrix(e,{});for(const[d,face]of Object.entries(e.faces||{})){const tx=texture(assets,resolveTexture(m,face.texture));if(!tx)continue;const local=V[d].map(([x0,y0,z0])=>new THREE.Vector3(x0?hi[0]:lo[0],y0?hi[1]:lo[1],z0?hi[2]:lo[2]).applyMatrix4(em)).map(v=>new THREE.Vector3((v.x-.5)*scale,y+v.y*height,(v.z-.5)*scale));const vs=local.map(v=>v.applyMatrix4(mx)),normal=new THREE.Vector3().crossVectors(vs[1].clone().sub(vs[0]),vs[2].clone().sub(vs[0])).normalize().toArray();scene.push({vs,uv:uvs(face),tx,alpha:1,dir:d,normal});n++}}return n}
// Vanilla ModelPart coordinates grow downward; reverse winding after the Y flip
// so converted entity textures retain the same corner mapping and face normals.
function entityVertex([x,y,z]){return new THREE.Vector3((x-8)/16,(16-y)/16,(z-8)/16)}
function addEntity(scene,assets,ent){const name=strip(ent.id,'entity'),f=path.join(assets,'models/entity',name+'.json');let m=null;if(fs.existsSync(f))m=json(f);const yaw=THREE.MathUtils.degToRad(-(+ent.rotation_y||0)),mx=new THREE.Matrix4().makeRotationY(yaw).setPosition(ent.x,ent.y,ent.z);if(m){let n=0;for(const e of m.elements||[]){const lo=e.from?.map(x=>(x-8)/16),hi=e.to?.map(x=>(x-8)/16);for(const[d,face]of Object.entries(e.faces||{})){const tx=entityTexture(assets,resolveTexture(m,face.texture));if(!tx)continue;const local=e.vertices?.[d]?.map(entityVertex).reverse()||V[d].map(([x,y,z])=>new THREE.Vector3(x?hi[0]:lo[0],y?hi[1]:lo[1],z?hi[2]:lo[2]));const vs=local.map(v=>v.applyMatrix4(mx)),normal=e.vertices?.[d]?new THREE.Vector3().crossVectors(vs[1].clone().sub(vs[0]),vs[2].clone().sub(vs[0])).normalize().toArray():faceNormal(d,mx);scene.push({vs,uv:uvs(face),tx,alpha:1,dir:d,normal});n++}}if(name==='hopper_minecart')n+=addEntityBlockModel(scene,assets,'hopper',mx);if(n)return'model'}let tx;if(name==='allay'){tx=entityTexture(assets,'allay/allay');if(tx){addBox(scene,[-.25,.18,-.16],[.25,.72,.16],tx,mx);addBox(scene,[-.22,.72,-.2],[.22,1.08,.2],tx,mx);addBox(scene,[-.62,.32,-.04],[-.25,.68,.04],tx,mx);addBox(scene,[.25,.32,-.04],[.62,.68,.04],tx,mx);addBox(scene,[-.31,1.08,-.03],[.31,1.13,.03],tx,mx);return'fallback'}}else if(name==='hopper_minecart'){tx=entityTexture(assets,'minecart/minecart');if(tx){addBox(scene,[-.49,0,-.49],[.49,.35,.49],tx,mx);addEntityBlockModel(scene,assets,'hopper',mx);return'fallback'}}tx=tx||entityTexture(assets,'minecart/minecart')||texture(assets,'stone');if(tx){addBox(scene,[-.125,0,-.125],[.125,.25,.125],tx,mx);return'marker'}return'missing'}
function addWater(scene,assets,b,water){let still=texture(assets,'water_still'),flow=texture(assets,'water_flow')||still;if(!still)return;still=waterTint(still);flow=waterTint(flow);const level=Math.min(15,+b.properties.level||0),h=level>=8?1:Math.max(.125,1-level/16),delta={east:[1,0,0],west:[-1,0,0],up:[0,1,0],down:[0,-1,0],south:[0,0,1],north:[0,0,-1]},mx=new THREE.Matrix4();for(const[d,q]of Object.entries(V)){const o=delta[d];if(water.has(`${b.x+o[0]},${b.y+o[1]},${b.z+o[2]}`))continue;scene.push({vs:q.map(([x,y,z])=>new THREE.Vector3(b.x+x,b.y+y*h,b.z+z)),uv:UV,tx:d==='up'||d==='down'?still:flow,alpha:.30,dir:d,normal:faceNormal(d,mx)})}}
function addRod(scene,assets,a,b){const tx=texture(assets,'piston_side');if(!tx)return;const ca=new THREE.Vector3(a.x+.5,a.y+.5,a.z+.5),cb=new THREE.Vector3(b.x+.5,b.y+.5,b.z+.5),lo=new THREE.Vector3(Math.min(ca.x,cb.x)-.125,Math.min(ca.y,cb.y)-.125,Math.min(ca.z,cb.z)-.125),hi=new THREE.Vector3(Math.max(ca.x,cb.x)+.125,Math.max(ca.y,cb.y)+.125,Math.max(ca.z,cb.z)+.125),mx=new THREE.Matrix4();for(const[d,q]of Object.entries(V))scene.push({vs:q.map(([x,y,z])=>new THREE.Vector3(x?hi.x:lo.x,y?hi.y:lo.y,z?hi.z:lo.z)),uv:UV,tx,alpha:1,dir:d,normal:faceNormal(d,mx)})}
function camera(view,s){const c=new THREE.Vector3(s.x/2,s.y/2,s.z/2);let w=view==='side'?s.z:s.x,h=view==='top'?s.z:s.y;if(view==='iso'){w=(s.x+s.z)/Math.sqrt(2);h=(s.x+2*s.y+s.z)/Math.sqrt(6);w*=1.02;h*=1.02}const cam=new THREE.OrthographicCamera(-w/2,w/2,h/2,-h/2,-100,100);if(view==='top'){cam.position.set(c.x,s.y+10,c.z);cam.up.set(0,0,-1)}else if(view==='front')cam.position.set(c.x,c.y,s.z+10);else if(view==='side')cam.position.set(s.x+10,c.y,c.z);else if(view==='iso')cam.position.set(s.x+10,s.y+10,s.z+10);else throw Error(`unknown view: ${view}`);cam.lookAt(c);cam.updateProjectionMatrix();cam.updateMatrixWorld(true);return{cam,w,h}}
function edge(a,b,p){return(p.x-a.x)*(b.y-a.y)-(p.y-a.y)*(b.x-a.x)}
function blend(p,x,y,c,a){if(x<0||y<0||x>=p.width||y>=p.height)return;const i=(y*p.width+x)*4,sa=c[3]/255*a,da=p.data[i+3]/255,oa=sa+da*(1-sa);if(!oa)return;for(let k=0;k<3;k++)p.data[i+k]=Math.round((c[k]*sa+p.data[i+k]*da*(1-sa))/oa);p.data[i+3]=Math.round(oa*255)}
function tri(p,pts,uv,tx,alpha,light){const ar=edge(pts[0],pts[1],pts[2]);if(Math.abs(ar)<1e-8)return;const x0=Math.max(0,Math.floor(Math.min(...pts.map(q=>q.x)))),x1=Math.min(p.width-1,Math.ceil(Math.max(...pts.map(q=>q.x)))),y0=Math.max(0,Math.floor(Math.min(...pts.map(q=>q.y)))),y1=Math.min(p.height-1,Math.ceil(Math.max(...pts.map(q=>q.y))));for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){const q={x:x+.5,y:y+.5},a=edge(pts[1],pts[2],q)/ar,b=edge(pts[2],pts[0],q)/ar,c=1-a-b;if(a<0||b<0||c<0)continue;const u=(uv[0][0]*a+uv[1][0]*b+uv[2][0]*c)/16,v=(uv[0][1]*a+uv[1][1]*b+uv[2][1]*c)/16,txx=Math.max(0,Math.min(tx.width-1,Math.floor(u*tx.width))),ty=Math.max(0,Math.min(tx.height-1,Math.floor(v*tx.height))),i=(ty*tx.width+txx)*4,color=tx.data.subarray(i,i+4);blend(p,x,y,light===1?color:[color[0]*light,color[1]*light,color[2]*light,color[3]],alpha)}}
function render(scene,view,s,px,out){const{cam,w,h}=camera(view,s),p=new PNG({width:Math.max(1,w*px),height:Math.max(1,h*px),colorType:6});p.data.fill(0);const lightDir=view==='iso'?new THREE.Vector3(.5,.8,.4).normalize():null,faces=scene.map(f=>{const pts=f.vs.map(v=>{const q=v.clone().applyMatrix4(cam.matrixWorldInverse).applyMatrix4(cam.projectionMatrix);return{x:(q.x+1)*p.width/2,y:(1-q.y)*p.height/2,z:q.z}});return{...f,pts,z:pts.reduce((n,q)=>n+q.z,0)/4+(f.depthBias||0)}}).sort((a,b)=>b.z-a.z);for(const f of faces){const normal=f.normal||FACE_NORMALS_BASE[f.dir],light=lightDir&&normal?.length?0.4+0.6*Math.max(0,lightDir.dot(new THREE.Vector3(...normal))):1;tri(p,[f.pts[0],f.pts[1],f.pts[2]],[f.uv[0],f.uv[1],f.uv[2]],f.tx,f.alpha,light);tri(p,[f.pts[0],f.pts[2],f.pts[3]],[f.uv[0],f.uv[2],f.uv[3]],f.tx,f.alpha,light)}fs.writeFileSync(out,PNG.sync.write(p))}
function run(file){const d=json(path.resolve(file)),assets=path.resolve(d.assets),scene=[],blocks=d.blocks.map(r=>({...r,properties:r.properties||{},x:r.x-d.min[0],y:r.y-d.min[1],z:r.z-d.min[2]})),entities=(d.entities||[]).map(r=>({...r,x:r.x-d.min[0],y:r.y-d.min[1],z:r.z-d.min[2]})),water=new Set(blocks.filter(b=>b.id==='minecraft:water'||b.id==='minecraft:bubble_column').map(b=>`${b.x},${b.y},${b.z}`));let missing=0,missingBy={};for(const b of blocks){if(b.id==='minecraft:water'||b.id==='minecraft:bubble_column'){addWater(scene,assets,b,water);continue}let n=0;for(const a of applications(assets,b))n+=addModel(scene,assets,b,a);if(!n){missing++;missingBy[b.id]=(missingBy[b.id]||0)+1}}for(const b of blocks.filter(x=>/:(sticky_)?piston$/.test(x.id)&&x.properties.extended==='true')){const head=blocks.find(h=>h.id==='minecraft:piston_head'&&Math.abs(h.x-b.x)+Math.abs(h.y-b.y)+Math.abs(h.z-b.z)===1);if(head)addRod(scene,assets,b,head)}const entityResults={};for(const ent of entities){const result=addEntity(scene,assets,ent);entityResults[result]=(entityResults[result]||0)+1}fs.mkdirSync(path.resolve(d.outputDir),{recursive:true});for(const v of d.views||['top','front','side'])render(scene,v,d.size,d.px,path.join(d.outputDir,`${d.prefix}_${v}.png`));console.log(JSON.stringify({faces:scene.length,missing,missingIds:Object.entries(missingBy).sort((a,b)=>b[1]-a[1]).slice(0,8),blocks:d.blocks.length,entities:entities.length,entityResults,views:d.views||['top','front','side']}))}
function main(a=process.argv.slice(2)){if(a.includes('--self-test')){for(const view of ['top','front','side','iso'])if(!(camera(view,{x:3,y:2,z:4}).cam instanceof THREE.OrthographicCamera))throw Error(`camera: ${view}`);console.log('Three.js orthographic renderer ready (top/front/side/iso)');return}const i=a.indexOf('--manifest');if(i<0||!a[i+1])throw Error('Usage: node render_3d.js --manifest scene.json');run(a[i+1])}
if(require.main===module)try{main()}catch(e){console.error(e.stack||e);process.exitCode=1}module.exports={main,model,applications,camera};
