#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),THREE=require('three');
const {PNG}=require('pngjs');
const J=new Map(),M=new Map(),T=new Map();
const V={east:[[1,0,0],[1,0,1],[1,1,1],[1,1,0]],west:[[0,0,1],[0,0,0],[0,1,0],[0,1,1]],up:[[0,1,0],[1,1,0],[1,1,1],[0,1,1]],down:[[0,0,1],[1,0,1],[1,0,0],[0,0,0]],south:[[1,0,1],[0,0,1],[0,1,1],[1,1,1]],north:[[0,0,0],[1,0,0],[1,1,0],[0,1,0]]};
const UV=[[0,16],[16,16],[16,0],[0,0]];
function json(f){if(!J.has(f))J.set(f,JSON.parse(fs.readFileSync(f)));return J.get(f)}
function strip(s,k='block'){return String(s||'').replace(/^minecraft:/,'').replace(new RegExp(`^${k}/`),'')}
function model(assets,id,seen=new Set()){
 id=strip(id);if(M.has(id))return M.get(id);if(seen.has(id))throw Error(`model parent cycle: ${id}`);
 const f=path.join(assets,'models/block',id+'.json');if(!fs.existsSync(f))return null;const r=json(f),p=r.parent?model(assets,r.parent,new Set([...seen,id])):null;
 const tx={...(p?.textures||{}),...(r.textures||{})};const out={textures:tx,elements:r.elements??p?.elements??[]};M.set(id,out);return out;
}
function resolveTexture(m,v){const seen=new Set();if(v&&typeof v==='object')v=v.sprite;while(typeof v==='string'&&v.startsWith('#')&&!seen.has(v)){seen.add(v);v=m.textures[v.slice(1)];if(v&&typeof v==='object')v=v.sprite}return typeof v==='string'?strip(v):null}
function match(w,p){if(!w)return true;if(w.OR)return w.OR.some(x=>match(x,p));if(w.AND)return w.AND.every(x=>match(x,p));return Object.entries(w).every(([k,v])=>String(v).split('|').includes(String(p[k])))}
function one(v){return Array.isArray(v)?(v.length?[v[0]]:[]):v?[v]:[]}
function applications(assets,b){const f=path.join(assets,'blockstates',strip(b.id)+'.json');if(!fs.existsSync(f))return[];const s=json(f),out=[];
 if(s.variants){let fallback;for(const[k,v]of Object.entries(s.variants)){fallback??=v;const q=Object.fromEntries(k.split(',').filter(Boolean).map(x=>x.split('=')));if(Object.entries(q).every(([a,z])=>String(b.properties[a])===z)){out.push(...one(v));fallback=null;break}}if(!out.length&&fallback)out.push(...one(fallback))}
 for(const p of s.multipart||[])if(match(p.when,b.properties))out.push(...one(p.apply));return out}
function texture(assets,n){n=strip(n);if(T.has(n))return T.get(n);const f=path.join(assets,'textures/block',n+'.png');if(!fs.existsSync(f))return null;const p=PNG.sync.read(fs.readFileSync(f)),o={width:p.width,height:Math.min(p.width,p.height),data:p.data};T.set(n,o);return o}
function waterTint(tx){if(tx.water)return tx.water;const data=Buffer.from(tx.data);for(let i=0;i<data.length;i+=4){const light=data[i]/255;data[i]=Math.round(64*light);data[i+1]=Math.round(118*light);data[i+2]=Math.round(228*light)}return tx.water={width:tx.width,height:tx.height,data}}
function uvs(face){const u=face.uv||[0,0,16,16];let q=[[u[0],u[3]],[u[2],u[3]],[u[2],u[1]],[u[0],u[1]]];for(let i=0;i<(+face.rotation||0)/90;i++)q=[q[1],q[2],q[3],q[0]];return q}
function matrix(e,a){const m=new THREE.Matrix4();if(e.rotation){const o=new THREE.Vector3(...(e.rotation.origin||[8,8,8])).multiplyScalar(1/16),axis=new THREE.Vector3(e.rotation.axis==='x'?1:0,e.rotation.axis==='y'?1:0,e.rotation.axis==='z'?1:0);m.premultiply(new THREE.Matrix4().makeTranslation(...o.clone().multiplyScalar(-1))).premultiply(new THREE.Matrix4().makeRotationAxis(axis,THREE.MathUtils.degToRad(e.rotation.angle||0))).premultiply(new THREE.Matrix4().makeTranslation(...o))}
 const c=.5,r=new THREE.Matrix4().makeTranslation(-c,-c,-c);r.premultiply(new THREE.Matrix4().makeRotationY(THREE.MathUtils.degToRad(-(a.y||0)))).premultiply(new THREE.Matrix4().makeRotationX(THREE.MathUtils.degToRad(a.x||0))).premultiply(new THREE.Matrix4().makeTranslation(c,c,c));return r.multiply(m)}
function addModel(scene,assets,b,a){const m=model(assets,a.model);if(!m)return 0;let n=0;for(const e of m.elements){const lo=e.from.map(x=>x/16),hi=e.to.map(x=>x/16),mx=matrix(e,a);for(const[d,f]of Object.entries(e.faces||{})){const tx=texture(assets,resolveTexture(m,f.texture));if(!tx)continue;const vs=V[d].map(([x,y,z])=>new THREE.Vector3(x?hi[0]:lo[0],y?hi[1]:lo[1],z?hi[2]:lo[2]).applyMatrix4(mx).add(new THREE.Vector3(b.x,b.y,b.z)));scene.push({vs,uv:uvs(f),tx,alpha:1});n++}}return n}
function addWater(scene,assets,b,water){let still=texture(assets,'water_still'),flow=texture(assets,'water_flow')||still;if(!still)return;still=waterTint(still);flow=waterTint(flow);const level=Math.min(15,+b.properties.level||0),h=level>=8?1:Math.max(.125,1-level/16),delta={east:[1,0,0],west:[-1,0,0],up:[0,1,0],down:[0,-1,0],south:[0,0,1],north:[0,0,-1]};for(const[d,q]of Object.entries(V)){const o=delta[d];if(water.has(`${b.x+o[0]},${b.y+o[1]},${b.z+o[2]}`))continue;scene.push({vs:q.map(([x,y,z])=>new THREE.Vector3(b.x+x,b.y+y*h,b.z+z)),uv:UV,tx:d==='up'||d==='down'?still:flow,alpha:.30})}}
function addRod(scene,assets,a,b){const tx=texture(assets,'piston_side');if(!tx)return;const ca=new THREE.Vector3(a.x+.5,a.y+.5,a.z+.5),cb=new THREE.Vector3(b.x+.5,b.y+.5,b.z+.5),lo=new THREE.Vector3(Math.min(ca.x,cb.x)-.125,Math.min(ca.y,cb.y)-.125,Math.min(ca.z,cb.z)-.125),hi=new THREE.Vector3(Math.max(ca.x,cb.x)+.125,Math.max(ca.y,cb.y)+.125,Math.max(ca.z,cb.z)+.125);for(const q of Object.values(V))scene.push({vs:q.map(([x,y,z])=>new THREE.Vector3(x?hi.x:lo.x,y?hi.y:lo.y,z?hi.z:lo.z)),uv:UV,tx,alpha:1})}
function camera(view,s){const c=new THREE.Vector3(s.x/2,s.y/2,s.z/2);let w=view==='side'?s.z:s.x,h=view==='top'?s.z:s.y;if(view==='iso'){w=(s.x+s.z)/Math.sqrt(2);h=(s.x+2*s.y+s.z)/Math.sqrt(6);w*=1.02;h*=1.02}const cam=new THREE.OrthographicCamera(-w/2,w/2,h/2,-h/2,-100,100);if(view==='top'){cam.position.set(c.x,s.y+10,c.z);cam.up.set(0,0,-1)}else if(view==='front')cam.position.set(c.x,c.y,s.z+10);else if(view==='side')cam.position.set(s.x+10,c.y,c.z);else if(view==='iso')cam.position.set(s.x+10,s.y+10,s.z+10);else throw Error(`unknown view: ${view}`);cam.lookAt(c);cam.updateProjectionMatrix();cam.updateMatrixWorld(true);return{cam,w,h}}
function edge(a,b,p){return(p.x-a.x)*(b.y-a.y)-(p.y-a.y)*(b.x-a.x)}
function blend(p,x,y,c,a){if(x<0||y<0||x>=p.width||y>=p.height)return;const i=(y*p.width+x)*4,sa=c[3]/255*a,da=p.data[i+3]/255,oa=sa+da*(1-sa);if(!oa)return;for(let k=0;k<3;k++)p.data[i+k]=Math.round((c[k]*sa+p.data[i+k]*da*(1-sa))/oa);p.data[i+3]=Math.round(oa*255)}
function tri(p,pts,uv,tx,alpha){const ar=edge(pts[0],pts[1],pts[2]);if(Math.abs(ar)<1e-8)return;const x0=Math.max(0,Math.floor(Math.min(...pts.map(q=>q.x)))),x1=Math.min(p.width-1,Math.ceil(Math.max(...pts.map(q=>q.x)))),y0=Math.max(0,Math.floor(Math.min(...pts.map(q=>q.y)))),y1=Math.min(p.height-1,Math.ceil(Math.max(...pts.map(q=>q.y))));for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){const q={x:x+.5,y:y+.5},a=edge(pts[1],pts[2],q)/ar,b=edge(pts[2],pts[0],q)/ar,c=1-a-b;if(a<0||b<0||c<0)continue;const u=(uv[0][0]*a+uv[1][0]*b+uv[2][0]*c)/16,v=(uv[0][1]*a+uv[1][1]*b+uv[2][1]*c)/16,txx=Math.max(0,Math.min(tx.width-1,Math.floor(u*tx.width))),ty=Math.max(0,Math.min(tx.height-1,Math.floor(v*tx.height))),i=(ty*tx.width+txx)*4;blend(p,x,y,tx.data.subarray(i,i+4),alpha)}}
function render(scene,view,s,px,out){const{cam,w,h}=camera(view,s),p=new PNG({width:Math.max(1,w*px),height:Math.max(1,h*px),colorType:6});p.data.fill(0);const faces=scene.map(f=>{const pts=f.vs.map(v=>{const q=v.clone().applyMatrix4(cam.matrixWorldInverse).applyMatrix4(cam.projectionMatrix);return{x:(q.x+1)*p.width/2,y:(1-q.y)*p.height/2,z:q.z}});return{...f,pts,z:pts.reduce((n,q)=>n+q.z,0)/4}}).sort((a,b)=>b.z-a.z);for(const f of faces){tri(p,[f.pts[0],f.pts[1],f.pts[2]],[f.uv[0],f.uv[1],f.uv[2]],f.tx,f.alpha);tri(p,[f.pts[0],f.pts[2],f.pts[3]],[f.uv[0],f.uv[2],f.uv[3]],f.tx,f.alpha)}fs.writeFileSync(out,PNG.sync.write(p))}
function run(file){const d=json(path.resolve(file)),assets=path.resolve(d.assets),scene=[],blocks=d.blocks.map(r=>({...r,properties:r.properties||{},x:r.x-d.min[0],y:r.y-d.min[1],z:r.z-d.min[2]})),water=new Set(blocks.filter(b=>b.id==='minecraft:water'||b.id==='minecraft:bubble_column').map(b=>`${b.x},${b.y},${b.z}`));let missing=0,missingBy={};for(const b of blocks){if(b.id==='minecraft:water'||b.id==='minecraft:bubble_column'){addWater(scene,assets,b,water);continue}let n=0;for(const a of applications(assets,b))n+=addModel(scene,assets,b,a);if(!n){missing++;missingBy[b.id]=(missingBy[b.id]||0)+1}}for(const b of blocks.filter(x=>/:(sticky_)?piston$/.test(x.id)&&x.properties.extended==='true')){const head=blocks.find(h=>h.id==='minecraft:piston_head'&&Math.abs(h.x-b.x)+Math.abs(h.y-b.y)+Math.abs(h.z-b.z)===1);if(head)addRod(scene,assets,b,head)}fs.mkdirSync(path.resolve(d.outputDir),{recursive:true});for(const v of d.views||['top','front','side'])render(scene,v,d.size,d.px,path.join(d.outputDir,`${d.prefix}_${v}.png`));console.log(JSON.stringify({faces:scene.length,missing,missingIds:Object.entries(missingBy).sort((a,b)=>b[1]-a[1]).slice(0,8),blocks:d.blocks.length,views:d.views||['top','front','side']}))}
function main(a=process.argv.slice(2)){if(a.includes('--self-test')){for(const view of ['top','front','side','iso'])if(!(camera(view,{x:3,y:2,z:4}).cam instanceof THREE.OrthographicCamera))throw Error(`camera: ${view}`);console.log('Three.js orthographic renderer ready (top/front/side/iso)');return}const i=a.indexOf('--manifest');if(i<0||!a[i+1])throw Error('Usage: node render_3d.js --manifest scene.json');run(a[i+1])}
if(require.main===module)try{main()}catch(e){console.error(e.stack||e);process.exitCode=1}module.exports={main,model,applications,camera};
